### ISSUE TITLE
pipeline

### ISSUE THREAD

**Issue by semperos** [rentpath/rp-condition-clj#4]
Two considerations for the `rp.condition.result/pipeline` function:

* [ ] How should the `pipeline` function handle functions (i.e., those functions passed to it as arguments) that do not return a `Result`?
* [ ] Relationship of `pipeline` to transducers?

**Comment by sbrauer** [comment]
Regarding the first point, perhaps `handle-result` should have that responsibility. In any event, it has the same issue. Since `pipeline` builds on `handle-result`, handling the issue there would handle it for `pipeline` as well.

**Comment by sbrauer** [comment]
Or maybe not. Going to del that comment (and this one, but adding it for notification purposes).

**Comment by sbrauer** [comment]
Also consider exception handling.
Perhaps `pipeline` should run each step in a `try` and return an error result when an exception is caught.

**Comment by semperos** [comment]
I'll add a point of caution on that front. Once we go from pure function composition to dealing with the dynamic scope of exceptions, especially if things in pipeline functions are happening in other threads, things become much harder to reason about and much more complex. The simplicity of the current `pipeline` is a strength on this front, in my opinion.

**Comment by semperos** [comment]
Group discussion:

1) If `handle-result` doesn't get a `Result`, an exception should be thrown to prevent the developer error from going unnoticed.

2) TO BE INSERTED BELOW by folks as they consider pipelines vs. transducers.

**Comment by sbrauer** [comment]
For reference: https://clojure.org/reference/transducers#_creating_transducers

**Comment by semperos** [comment]
Cleaning up my GitHub queues :)
